# Generated by Django 2.0.3 on 2018-04-09 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180409_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parrent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Comment'),
        ),
    ]
