# Generated by Django 2.0.3 on 2018-03-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180317_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='preview',
            field=models.ImageField(default='', upload_to='static/previews'),
        ),
    ]
