# Generated by Django 2.0.3 on 2018-03-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180317_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='preview',
            field=models.ImageField(default='', upload_to='previews'),
        ),
    ]
