# Generated by Django 2.0.4 on 2018-04-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180409_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseevent',
            name='num_of_participants',
            field=models.IntegerField(default=1),
        ),
    ]
