# Generated by Django 2.0.4 on 2018-04-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_baseevent_num_of_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseevent',
            name='num_of_participants',
            field=models.IntegerField(default=0),
        ),
    ]
