# Generated by Django 2.0.3 on 2018-03-18 06:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_eventsubscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventsubscription',
            unique_together={('subscriber', 'event')},
        ),
    ]
