# Generated by Django 2.0.3 on 2018-03-22 10:30

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180318_0645'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('event_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
