# Generated by Django 2.0.4 on 2018-05-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180414_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
