# Generated by Django 2.0.3 on 2018-04-05 13:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_auto_20180405_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField()),
                ('preview', models.ImageField(default='', upload_to='previews')),
                ('date', models.DateTimeField(default=datetime.date.today)),
            ],
            managers=[
                ('event_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='preview',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseEvent')),
            ],
            bases=('main.baseevent',),
            managers=[
                ('event_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='baseevent',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='baseevent_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BaseEvent'),
            preserve_default=False,
        ),
    ]
