# Generated by Django 2.0.3 on 2018-04-05 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180405_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.BaseEvent'),
        ),
    ]
