# Generated by Django 2.0.4 on 2018-05-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180505_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='num_of_placess',
            field=models.IntegerField(default=0),
        ),
    ]
