# Generated by Django 2.0.3 on 2018-04-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180405_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubscription',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.BaseEvent'),
        ),
    ]
