# Generated by Django 2.0.4 on 2018-05-06 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_baseeventcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseeventcategory',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.BaseEvent'),
        ),
    ]
