# Generated by Django 2.0.4 on 2018-05-06 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180506_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseeventcategory',
            name='event',
        ),
        migrations.AddField(
            model_name='baseevent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.BaseEventCategory'),
        ),
    ]
